import type { Metadata } from 'next';
import { InspectorProvider } from '@hyperse/next-inspector/client';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <InspectorProvider />
        {children}
      </body>
    </html>
  );
}
