import type { Metadata } from 'next';
import { InspectorProvider } from '@hyperse/next-inspector/client';
import { ProviderWrapper } from '../components/Providers/ProviderWrapper';
import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const isDev = process.env.NODE_ENV === 'development';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/**
         * Only inject InspectorProvider in development environment
         */}
        {isDev && <InspectorProvider />}
        <ProviderWrapper>{children}</ProviderWrapper>
      </body>
    </html>
  );
}
